name: TorchDetectAML
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.1.0 
  - torchvision=0.3.0 
  - cudatoolkit=9.0
  - nb_conda=2.2.1
  - matplotlib=3.1.0
  - Cython=0.29.10
  - pip:
    - prompt_toolkit>=2.0.7
    - azureml-sdk[notebooks]
    - papermill==0.14.2
    - python-dotenv==0.10.1
    - azure-cli
    
